// Generated by Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import CoreGraphics;
@import Foundation;
#endif

#import <SFKit/SFKit.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SFKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif





@class UIColor;
@class UIView;
@class NSCoder;

SWIFT_CLASS("_TtC5SFKit8SFButton")
@interface SFButton : UIButton
@property (nonatomic, strong) UIColor * _Null_unspecified tintColor;
@property (nonatomic) NSInteger buttonKindRawValue;
/// Frame must be overriden to ensure the elliptical boolean remains equivalent.
@property (nonatomic) CGRect frame;
@property (nonatomic, getter=isEnabled) BOOL enabled;
@property (nonatomic, getter=isSelected) BOOL selected;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
- (void)prepareForInterfaceBuilder;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (void)appearanceStyleDidChange:(SFAppearanceStyle)previousAppearanceStyle;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, Kind) {
  KindSquare = 0,
  KindRounded = 1,
};


SWIFT_CLASS("_TtC5SFKit24SFCollectionReusableView") SWIFT_DEPRECATED_MSG("use UICollectionReusableView instead")
@interface SFCollectionReusableView : UICollectionReusableView
- (void)prepareForInterfaceBuilder;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionViewLayout;

SWIFT_CLASS("_TtC5SFKit16SFCollectionView") SWIFT_DEPRECATED_MSG("use UICollectionView instead")
@interface SFCollectionView : UICollectionView
- (void)prepareForInterfaceBuilder;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (nonnull instancetype)initWithFrame:(CGRect)frame collectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5SFKit20SFCollectionViewCell") SWIFT_DEPRECATED_MSG("use UICollectionViewCell instead")
@interface SFCollectionViewCell : UICollectionViewCell
- (void)prepareForInterfaceBuilder;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;

SWIFT_CLASS("_TtC5SFKit26SFCollectionViewController") SWIFT_DEPRECATED_MSG("use UICollectionViewController instead")
@interface SFCollectionViewController : UICollectionViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithCollectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
@class CIColor;

/// Subclasses <code>UIColor</code> to provide a more fine-tuned selection of static color variables. <code>SFColor</code> also provides an array of more specific color brightness adjustments.
/// Static colors are available as computed properties which are subject to change between different releases of <em>SFKit</em>. Any change made to the statically available color scheme is guranteed to be visually compatible, meaning the design will still work as intended.
/// The color values exposed by <code>SFColor</code> are guaranteed to be reflective of the current global appearance style. The color cannot be expected to update autonomously in the event of an appearance style change, therefore colors must be updated by setting the statically defined colors again. The caller is fully responsible for color changes to take place.
SWIFT_CLASS("_TtC5SFKit7SFColor") SWIFT_DEPRECATED_MSG("use SFColorMetrics instead")
@interface SFColor : UIColor
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFColor * _Nonnull redColor;)
+ (SFColor * _Nonnull)redColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFColor * _Nonnull orangeColor;)
+ (SFColor * _Nonnull)orangeColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFColor * _Nonnull yellowColor;)
+ (SFColor * _Nonnull)yellowColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFColor * _Nonnull greenColor;)
+ (SFColor * _Nonnull)greenColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFColor * _Nonnull blueColor;)
+ (SFColor * _Nonnull)blueColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFColor * _Nonnull purpleColor;)
+ (SFColor * _Nonnull)purpleColor SWIFT_WARN_UNUSED_RESULT;
/// An off-white color.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFColor * _Nonnull whiteColor;)
+ (SFColor * _Nonnull)whiteColor SWIFT_WARN_UNUSED_RESULT;
/// A light gray.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFColor * _Nonnull lightGrayColor;)
+ (SFColor * _Nonnull)lightGrayColor SWIFT_WARN_UNUSED_RESULT;
/// A medium colored gray.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFColor * _Nonnull grayColor;)
+ (SFColor * _Nonnull)grayColor SWIFT_WARN_UNUSED_RESULT;
/// A darker than medium gray.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFColor * _Nonnull darkGrayColor;)
+ (SFColor * _Nonnull)darkGrayColor SWIFT_WARN_UNUSED_RESULT;
/// Depp black color which is adaptive.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFColor * _Nonnull blackColor;)
+ (SFColor * _Nonnull)blackColor SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithWhite:(CGFloat)white alpha:(CGFloat)alpha OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithHue:(CGFloat)hue saturation:(CGFloat)saturation brightness:(CGFloat)brightness alpha:(CGFloat)alpha OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRed:(CGFloat)red green:(CGFloat)green blue:(CGFloat)blue alpha:(CGFloat)alpha OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDisplayP3Red:(CGFloat)displayP3Red green:(CGFloat)green blue:(CGFloat)blue alpha:(CGFloat)alpha OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=10.0);
- (nonnull instancetype)initWithCGColor:(CGColorRef _Nonnull)cgColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPatternImage:(UIImage * _Nonnull)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCIColor:(CIColor * _Nonnull)ciColor OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=5.0);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC5SFKit11SFImageView") SWIFT_DEPRECATED_MSG("use UIImageView instead")
@interface SFImageView : UIImageView
- (void)prepareForInterfaceBuilder;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIFont;

SWIFT_CLASS("_TtC5SFKit7SFLabel")
@interface SFLabel : UILabel
@property (nonatomic, strong) UIFont * _Null_unspecified font;
- (void)prepareForInterfaceBuilder;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (void)appearanceStyleDidChange:(SFAppearanceStyle)previousAppearanceStyle;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5SFKit6SFView")
@interface SFView : UIView
@property (nonatomic) BOOL shouldEnforceAppearance;
/// Corner radius of the view.
@property (nonatomic) CGFloat cornerRadius;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5SFKit9SFPolygon")
@interface SFPolygon : SFView
/// Stroke color of the resulting polygon line.
@property (nonatomic, strong) UIColor * _Nullable strokeColor;
/// Line width of the resultant polygon.
@property (nonatomic) CGFloat lineWidth;
/// Intrinsic content size of the resultant polygon.
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)sizeToFit;
- (void)drawRect:(CGRect)rect;
@end


/// Straight line that is either horizontal or vertical, with horizontal being the most common. If an angled line is desired, use <code>SFPolygon</code> directly.
SWIFT_CLASS("_TtC5SFKit6SFLine")
@interface SFLine : SFPolygon
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5SFKit15SFNavigationBar")
@interface SFNavigationBar : UINavigationBar
- (void)prepareForInterfaceBuilder;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (void)appearanceStyleDidChange:(SFAppearanceStyle)previousAppearanceStyle;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;

SWIFT_CLASS("_TtC5SFKit22SFNavigationController")
@interface SFNavigationController : UINavigationController
- (void)viewDidLoad;
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


/// A discrete unit for an <code>SFOnboardingStage</code>. A particular stage will have cards associated with it, as this structure represents the content component.
SWIFT_CLASS("_TtC5SFKit16SFOnboardingCard")
@interface SFOnboardingCard : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Modal view controller that has been designed to provide a concrete and consistent onboarding experience. The design is referenced from an internal resource, thus limiting complete customization to a certain degree.
/// <h1>Onboarding</h1>
/// Launch time is your first opportunity to onboard new users and reconnect with returning ones. Use <code>SFOnboardingController</code> to design a launch experience that’s fast, fun, and educational.
SWIFT_CLASS("_TtC5SFKit22SFOnboardingController")
@interface SFOnboardingController : UIViewController
/// Child view controller that is responsible for the status bar.
@property (nonatomic, readonly, strong) UIViewController * _Nullable childViewControllerForStatusBarStyle;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@protocol UIViewControllerContextTransitioning;

/// View controller transition animation that is associated with a stack push transition.
/// <em>Transition Duration Values</em>:
/// <ul>
///   <li>
///     Presenting: 0.6 sec
///   </li>
///   <li>
///     Dismissing: 0.53 sec
///   </li>
/// </ul>
SWIFT_CLASS("_TtC5SFKit24SFOnboardingPushAnimator")
@interface SFOnboardingPushAnimator : NSObject <UIViewControllerAnimatedTransitioning>
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> _Nullable)transitionContext SWIFT_WARN_UNUSED_RESULT;
- (void)animateTransition:(id <UIViewControllerContextTransitioning> _Nonnull)transitionContext;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UITableView;
@class UITableViewCell;

SWIFT_CLASS("_TtC5SFKit31SFOnboardingStageViewController")
@interface SFOnboardingStageViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
/// Primary button title that will be presented to users.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified primaryButton;
/// Secondary button title that will be presented to users.
/// note:
/// When set to <code>nil</code> the secondary button is hidden.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified secondaryButton;
/// Leading button title that will be presented to users.
/// note:
/// When set to <code>nil</code> the leading button is hidden.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified leadingButton;
/// Trailing button title that will be presented to users.
/// note:
/// When set to <code>nil</code> the trailing button is hidden.
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified trailingButton;
/// Accessory label that acts as a secondary UI element which can be found above the <code>primaryControl</code>.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified accessoryLabel;
/// Contains the <code>leadingButton</code> and the <code>trailingButton</code>.
/// note:
/// When the leading & trailing buttons are both hidden, this view is also hidden.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified topContainer;
/// Contains the <code>primaryButton</code> and the <code>secondaryButton</code>.
/// note:
/// When the primary & secondary buttons are both hidden, this view is also hidden.
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified bottomContainer;
/// Displays the cards.
@property (nonatomic, strong) IBOutlet UITableView * _Null_unspecified tableView;
- (void)viewDidLoad;
- (void)appearanceStyleDidChange:(SFAppearanceStyle)previousAppearanceStyle;
- (void)didReceiveMemoryWarning;
- (void)primaryButtonAction:(id _Nullable)sender;
- (void)secondaryButtonAction:(id _Nullable)sender;
- (void)leadingButtonAction:(id _Nullable)sender;
- (void)trailingButtonAction:(id _Nullable)sender;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5SFKit25SFOnboardingTextFieldCard")
@interface SFOnboardingTextFieldCard : SFOnboardingCard
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UITextField;

SWIFT_CLASS("_TtC5SFKit29SFOnboardingTextFieldCardCell")
@interface SFOnboardingTextFieldCardCell : UITableViewCell
/// Label that will present the title.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified titleLabel;
/// Text field from which input will be taken.
@property (nonatomic, strong) IBOutlet UITextField * _Null_unspecified textField;
- (void)appearanceStyleDidChange:(SFAppearanceStyle)previousAppearanceStyle;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5SFKit21SFOnboardingTitleCard")
@interface SFOnboardingTitleCard : SFOnboardingCard
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5SFKit25SFOnboardingTitleCardCell")
@interface SFOnboardingTitleCardCell : UITableViewCell
/// Label that will present the title.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified titleLabel;
/// Label that will present the description.
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified detailLabel;
/// Image view that will display the image.
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified embeddedImageView;
- (void)appearanceStyleDidChange:(SFAppearanceStyle)previousAppearanceStyle;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5SFKit32SFOnboardingTransitionController")
@interface SFOnboardingTransitionController : NSObject <UIViewControllerTransitioningDelegate>
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC5SFKit8SFTabBar")
@interface SFTabBar : UITabBar
- (void)prepareForInterfaceBuilder;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (void)appearanceStyleDidChange:(SFAppearanceStyle)previousAppearanceStyle;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5SFKit11SFTableView") SWIFT_DEPRECATED_MSG("use UITableView instead")
@interface SFTableView : UITableView
- (void)prepareForInterfaceBuilder;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (nonnull instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5SFKit15SFTableViewCell") SWIFT_DEPRECATED_MSG("use UITableViewCell instead")
@interface SFTableViewCell : UITableViewCell
- (void)prepareForInterfaceBuilder;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5SFKit21SFTableViewController") SWIFT_DEPRECATED_MSG("use UITableViewController instead")
@interface SFTableViewController : UITableViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5SFKit27SFTableViewHeaderFooterView") SWIFT_DEPRECATED_MSG("use UITableViewHeaderFooterView instead")
@interface SFTableViewHeaderFooterView : UITableViewHeaderFooterView
- (void)prepareForInterfaceBuilder;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (nonnull instancetype)initWithReuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5SFKit11SFTextField")
@interface SFTextField : UITextField <UITextFieldDelegate>
- (void)prepareForInterfaceBuilder;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (void)appearanceStyleDidChange:(SFAppearanceStyle)previousAppearanceStyle;
- (CGRect)textRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)editingRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSTextContainer;

SWIFT_CLASS("_TtC5SFKit10SFTextView")
@interface SFTextView : UITextView
/// Boolean value determining whether or not the appearance will be forcefully applied.
@property (nonatomic) BOOL shouldEnforceAppearance;
/// Corner radius of the text view.
@property (nonatomic) CGFloat cornerRadius;
/// Edge inset for the top of the embedded text container.
@property (nonatomic) CGFloat topTextContainerInset;
/// Edge inset for the bottom of the embedded text container.
@property (nonatomic) CGFloat bottomTextContainerInset;
/// Edge inset for the left of the embedded text container.
@property (nonatomic) CGFloat leftTextContainerInset;
/// Edge inset for the right of the embedded text container.
@property (nonatomic) CGFloat rightTextContainerInset;
- (void)prepareForInterfaceBuilder;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=7.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC5SFKit16SFViewController") SWIFT_DEPRECATED_MSG("use UIViewController instead")
@interface SFViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIVisualEffect;

SWIFT_CLASS("_TtC5SFKit18SFVisualEffectView")
@interface SFVisualEffectView : UIVisualEffectView
/// Boolean value indicating if the visual effect view uses an extra light blur effect.
@property (nonatomic) BOOL isExtraLight;
- (void)appearanceStyleDidChange:(SFAppearanceStyle)previousAppearanceStyle;
- (nonnull instancetype)initWithEffect:(UIVisualEffect * _Nullable)effect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



enum UIColorMetricsHue : NSInteger;

SWIFT_CLASS("_TtC5SFKit14UIColorMetrics")
@interface UIColorMetrics : NSObject
/// The default color metrics object for content. Initialized with <code>SFAppearance.global</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) UIColorMetrics * _Nonnull default_;)
+ (UIColorMetrics * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
/// Creates a color metrics object for the provided appearance.
- (nonnull instancetype)initForAppearance:(SFAppearance * _Nonnull)appearance;
/// Creates a color metrics object for the specified appearance style.
- (nonnull instancetype)initForAppearanceStyle:(SFAppearanceStyle)appearanceStyle OBJC_DESIGNATED_INITIALIZER;
/// Returns a color adapted for the appearance style the receiver was initialized for.
/// \param hue Color that is relative to the <em>light</em> appearance style.
///
///
/// returns:
/// Color that has been adapted for the initially specified appearance style.
- (UIColor * _Nonnull)colorForRelativeHue:(enum UIColorMetricsHue)hue SWIFT_WARN_UNUSED_RESULT;
/// Returns a color adapted for the appearance style the receiver was initialized for.
/// \param color Color that is relative to a particular <code>UIColorMetrics</code> instance.
///
/// \param colorMetrics <code>UIColorMetrics</code> instance for which <code>color</code> is relative to. This will be used to convert the color between appearance styles.
///
///
/// returns:
/// Color that has been adapted for the appearance style.
- (UIColor * _Nonnull)colorForColor:(UIColor * _Nonnull)color relativeTo:(UIColorMetrics * _Nonnull)colorMetrics SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

/// Enumeration containing range of colors.
typedef SWIFT_ENUM(NSInteger, UIColorMetricsHue) {
  UIColorMetricsHueRed = 0,
  UIColorMetricsHueOrange = 1,
  UIColorMetricsHueYellow = 2,
  UIColorMetricsHueGreen = 3,
  UIColorMetricsHueTealBlue = 4,
  UIColorMetricsHueBlue = 5,
  UIColorMetricsHueDarkBlue = 6,
  UIColorMetricsHuePurple = 7,
  UIColorMetricsHuePink = 8,
  UIColorMetricsHueWhite = 9,
  UIColorMetricsHueExtraLightGray = 10,
  UIColorMetricsHueLightGray = 11,
  UIColorMetricsHueGray = 12,
  UIColorMetricsHueDarkGray = 13,
  UIColorMetricsHueExtraDarkGray = 14,
  UIColorMetricsHueBlack = 15,
};









#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
